package model.AM;

import model.DATA.UtilisateurData;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 22 13:26:03 CEST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UtilisateurAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UtilisateurAMImpl() {
    }

    /**
     * Container's getter for UtilisateurVO1.
     * @return UtilisateurVO1
     */
    public ViewObjectImpl getUtilisateurVO1() {
        return (ViewObjectImpl) findViewObject("UtilisateurVO1");
    }

    /**
     * Container's getter for PaiementVO1.
     * @return PaiementVO1
     */
    public ViewObjectImpl getPaiementVO1() {
        return (ViewObjectImpl) findViewObject("PaiementVO1");
    }

    /**
     * Container's getter for ProfileuserVO1.
     * @return ProfileuserVO1
     */
    public ViewObjectImpl getProfileuserVO1() {
        return (ViewObjectImpl) findViewObject("ProfileuserVO1");
    }

    /**
     * Container's getter for UtilisateurVO2.
     * @return UtilisateurVO2
     */
    public ViewObjectImpl getUtilisateurVO2() {
        return (ViewObjectImpl) findViewObject("UtilisateurVO2");
    }

    /**
     * Container's getter for SysC0014166Link.
     * @return SysC0014166Link
     */
    public ViewLinkImpl getSysC0014166Link() {
        return (ViewLinkImpl) findViewLink("SysC0014166Link");
    }

    /**
     * Container's getter for SysC0014138Link.
     * @return SysC0014138Link
     */
    public ViewLinkImpl getSysC0014138Link() {
        return (ViewLinkImpl) findViewLink("SysC0014138Link");
    }
    
    
    public UtilisateurData connexion (String _username , String _password) {
            System.out.println("inside corona");
            UtilisateurData user = null;
            ViewObject vo = this.getUtilisateurVO1();
            ViewCriteria vc = vo.createViewCriteria();
            ViewCriteriaRow vcr = vc.createViewCriteriaRow();
            vcr.setAttribute("Username", _username);
            vcr.setAttribute("Mdp", _password);
            vc.add(vcr);
            vo.applyViewCriteria(vc);
            vo.executeQuery();
            if (vo.hasNext()) {
                user = new UtilisateurData();
                Row row = vo.next();
                user.setUsername(row.getAttribute("Username").toString());
            }
            return user;
        }
}

